services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: chainlink
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: chainlink
    volumes:
      - chainlink-db:/var/lib/postgresql/data
    ports:
      - "5432:5432" # optional for debugging
    networks:
      - chainlink-network

  chainlink:
    image: smartcontract/chainlink:2.20.0
    restart: always
    depends_on:
      - db
    ports:
      - "6688:6688"
    volumes:
      - .:/chainlink:ro
    working_dir: /chainlink
    command: node -config config.toml -secrets secrets.toml start -a api.txt
    networks:
      - chainlink-network

volumes:
  chainlink-db:

networks:
  chainlink-network:
    driver: bridge
